# Generated by Django 5.1.3 on 2024-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdesk',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('editor', 'Editor'), ('zonal_editor', 'Zonal Editor'), ('regional_editor', 'Regional Editor'), ('national_editor', 'National Editor'), ('desk_head', 'Desk Head')], default='reporter', max_length=20),
        ),
    ]
